targets = main.bin
CC = gcc
C_OPTS = -std=gnu11 -g -Wall -Wextra -Werror -Wformat-security -Wfloat-equal -Wshadow -Wconversion -Wlogical-not-parentheses -Wnull-dereference 

all: clean prep compile run

clean:
	rm -rf dist
prep:
	mkdir dist
compile: main.bin

main.bin: src/main.c

run: clean prep compile
	./dist/main.bin
doxygen:
	doxygen Doxyfile
format: #TODO

tidy: # TODO

